services:
    dmzx.groupsintopic.listener:
        class: dmzx\groupsintopic\event\listener
        arguments:
            - @cache
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }
